name: Yap CI

on: [push]

jobs:
  build-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 17
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - name: npm install, test, and build
        working-directory: ./yap-react
        run: |
          npm i
          npm run test
          npm run build
        env:
          CI: true

  build-lit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 17
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - name: npm install, test, and build
        working-directory: ./yap-lit
        run: |
          npm i
          npm run test
          npm run build
        env:
          CI: true